"""One-shot script: generate per-word IPA (en-US) for the 72 fixed practice
sentences and emit the new PRACTICE_SENTENCES structure.

Strategy (see reviews/2026-06-07_full_scan_scoring.md design):
  - eng_to_ipa converts the WHOLE sentence (it does context-aware disambiguation,
    e.g. "I read it yesterday" -> rɛd), then we align the result word-by-word to
    the original .split() tokens (counts match in practice).
  - Punctuation is stripped from each token's IPA.
  - Words eng_to_ipa cannot resolve come back with a trailing '*'; we collect
    those as `unknown` so a human/LLM can fill them in (rare for common English).

Run from repo root:  python -m scripts.gen_ipa            (preview)
                     python -m scripts.gen_ipa --write    (rewrite the corpus)

This is a build-time tool. Runtime never imports eng_to_ipa.
"""
import re
import sys

import eng_to_ipa as ipa

from assessment.scenarios import PRACTICE_SENTENCES

_PUNCT = ".,!?;:\"'"

# Map academic IPA symbols to their learner-dictionary equivalents. eng_to_ipa
# emits the strict alveolar approximant ɹ for English /r/; Oxford/Cambridge
# learner dictionaries simplify it to a plain r, which is what users expect.
_IPA_NORMALIZE = {
    "ɹ": "r",
}


def _normalize_ipa(s: str) -> str:
    """Rewrite strict IPA symbols to learner-dictionary conventions."""
    for src, dst in _IPA_NORMALIZE.items():
        s = s.replace(src, dst)
    return s

# Manual IPA (en-US) for words eng_to_ipa can't resolve — proper nouns and
# hyphenated compounds it doesn't carry. Far cheaper than wiring an LLM for 4
# words; verified against standard dictionaries.
_MANUAL_IPA = {
    "netflix": "ˈnɛtflɪks",
    "carry-on": "ˈkɛriˌɑn",
    "deadlift": "ˈdɛdˌlɪft",
    "mid-size": "ˈmɪdˌsaɪz",
}


def _clean(token: str) -> str:
    """Strip surrounding punctuation from an IPA/word token."""
    return token.strip(_PUNCT)


def sentence_to_words(sentence: str) -> tuple[list[dict], list[str]]:
    """Return ([{word, ipa_us}], unknown_words) for one sentence.

    `word` is the clean display token (no punctuation); `ipa_us` is its IPA.
    """
    tokens = sentence.split()
    ipa_str = ipa.convert(sentence)
    ipa_tokens = ipa_str.split()

    words, unknown = [], []
    # Counts match in the corpus, but guard so a mismatch degrades gracefully
    # (missing IPA -> empty string, never an index error).
    for i, tok in enumerate(tokens):
        clean_word = _clean(tok)
        raw_ipa = ipa_tokens[i] if i < len(ipa_tokens) else ""
        clean_ipa = _clean(raw_ipa)
        if clean_ipa.endswith("*"):  # eng_to_ipa couldn't resolve this word
            manual = _MANUAL_IPA.get(clean_word.lower())
            if manual:
                clean_ipa = manual
            else:
                unknown.append(clean_word)
                clean_ipa = ""
        clean_ipa = _normalize_ipa(clean_ipa)
        words.append({"word": clean_word, "ipa_us": clean_ipa})
    return words, unknown


def build() -> tuple[dict, list[str]]:
    new_corpus, all_unknown = {}, []
    for scenario_id, sentences in PRACTICE_SENTENCES.items():
        new_sentences = []
        for s in sentences:
            # Corpus may already be in the new {text, words} shape (idempotent
            # regeneration) or the legacy plain-string shape.
            text = s["text"] if isinstance(s, dict) else s
            words, unknown = sentence_to_words(text)
            new_sentences.append({"text": text, "words": words})
            all_unknown.extend(unknown)
        new_corpus[scenario_id] = new_sentences
    return new_corpus, all_unknown


def _render_data_file(corpus: dict) -> str:
    """Render corpus as a standalone data module."""
    import json
    body = json.dumps(corpus, ensure_ascii=False, indent=4)
    return (
        '"""Auto-generated by scripts/gen_ipa.py — do NOT edit by hand.\n\n'
        "Practice sentences with per-word en-US IPA. Regenerate with:\n"
        "    python -m scripts.gen_ipa --write\n"
        '"""\n\n'
        f"PRACTICE_SENTENCES = {body}\n"
    )


def main():
    corpus, unknown = build()
    total = sum(len(v) for v in corpus.values())
    print(f"# {total} sentences across {len(corpus)} scenarios", file=sys.stderr)
    if unknown:
        print(f"# UNKNOWN words needing manual IPA: {sorted(set(unknown))}",
              file=sys.stderr)
    else:
        print("# all words resolved (eng_to_ipa + manual overrides)", file=sys.stderr)

    if "--write" in sys.argv:
        import os
        out = os.path.join(os.path.dirname(__file__), "..", "assessment",
                           "scenarios", "practice_sentences_data.py")
        out = os.path.abspath(out)
        with open(out, "w", encoding="utf-8") as f:
            f.write(_render_data_file(corpus))
        print(f"# wrote {out}", file=sys.stderr)
        return

    # Preview the first scenario so quality can be eyeballed.
    import json
    first = next(iter(corpus))
    print(json.dumps({first: corpus[first]}, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
