"""Auto-generated by scripts/gen_ipa.py — do NOT edit by hand.

Practice sentences with per-word en-US IPA. Regenerate with:
    python -m scripts.gen_ipa --write
"""

PRACTICE_SENTENCES = {
    "coffee_shop": [
        {
            "text": "I'd like a medium latte with oat milk, please.",
            "words": [
                {
                    "word": "I'd",
                    "ipa_us": "aɪd"
                },
                {
                    "word": "like",
                    "ipa_us": "laɪk"
                },
                {
                    "word": "a",
                    "ipa_us": "ə"
                },
                {
                    "word": "medium",
                    "ipa_us": "ˈmidiəm"
                },
                {
                    "word": "latte",
                    "ipa_us": "ˈlɑˌteɪ"
                },
                {
                    "word": "with",
                    "ipa_us": "wɪθ"
                },
                {
                    "word": "oat",
                    "ipa_us": "oʊt"
                },
                {
                    "word": "milk",
                    "ipa_us": "mɪlk"
                },
                {
                    "word": "please",
                    "ipa_us": "pliz"
                }
            ]
        },
        {
            "text": "Could I also get a blueberry muffin to go?",
            "words": [
                {
                    "word": "Could",
                    "ipa_us": "kʊd"
                },
                {
                    "word": "I",
                    "ipa_us": "aɪ"
                },
                {
                    "word": "also",
                    "ipa_us": "ˈɔlsoʊ"
                },
                {
                    "word": "get",
                    "ipa_us": "gɪt"
                },
                {
                    "word": "a",
                    "ipa_us": "ə"
                },
                {
                    "word": "blueberry",
                    "ipa_us": "ˈbluˌbɛri"
                },
                {
                    "word": "muffin",
                    "ipa_us": "ˈməfən"
                },
                {
                    "word": "to",
                    "ipa_us": "tɪ"
                },
                {
                    "word": "go",
                    "ipa_us": "goʊ"
                }
            ]
        },
        {
            "text": "Do you have any seasonal specials today?",
            "words": [
                {
                    "word": "Do",
                    "ipa_us": "du"
                },
                {
                    "word": "you",
                    "ipa_us": "ju"
                },
                {
                    "word": "have",
                    "ipa_us": "hæv"
                },
                {
                    "word": "any",
                    "ipa_us": "ˈɛni"
                },
                {
                    "word": "seasonal",
                    "ipa_us": "ˈsizənəl"
                },
                {
                    "word": "specials",
                    "ipa_us": "ˈspɛʃəlz"
                },
                {
                    "word": "today",
                    "ipa_us": "təˈdeɪ"
                }
            ]
        },
        {
            "text": "Can I pay with my phone?",
            "words": [
                {
                    "word": "Can",
                    "ipa_us": "kən"
                },
                {
                    "word": "I",
                    "ipa_us": "aɪ"
                },
                {
                    "word": "pay",
                    "ipa_us": "peɪ"
                },
                {
                    "word": "with",
                    "ipa_us": "wɪθ"
                },
                {
                    "word": "my",
                    "ipa_us": "maɪ"
                },
                {
                    "word": "phone",
                    "ipa_us": "foʊn"
                }
            ]
        }
    ],
    "grocery": [
        {
            "text": "Excuse me, where can I find the pasta sauce?",
            "words": [
                {
                    "word": "Excuse",
                    "ipa_us": "ɪkˈskjuz"
                },
                {
                    "word": "me",
                    "ipa_us": "mi"
                },
                {
                    "word": "where",
                    "ipa_us": "wɛr"
                },
                {
                    "word": "can",
                    "ipa_us": "kən"
                },
                {
                    "word": "I",
                    "ipa_us": "aɪ"
                },
                {
                    "word": "find",
                    "ipa_us": "faɪnd"
                },
                {
                    "word": "the",
                    "ipa_us": "ðə"
                },
                {
                    "word": "pasta",
                    "ipa_us": "ˈpɑstə"
                },
                {
                    "word": "sauce",
                    "ipa_us": "sɔs"
                }
            ]
        },
        {
            "text": "Do you have any organic vegetables in stock?",
            "words": [
                {
                    "word": "Do",
                    "ipa_us": "du"
                },
                {
                    "word": "you",
                    "ipa_us": "ju"
                },
                {
                    "word": "have",
                    "ipa_us": "hæv"
                },
                {
                    "word": "any",
                    "ipa_us": "ˈɛni"
                },
                {
                    "word": "organic",
                    "ipa_us": "ɔrˈgænɪk"
                },
                {
                    "word": "vegetables",
                    "ipa_us": "ˈvɛʤtəbəlz"
                },
                {
                    "word": "in",
                    "ipa_us": "ɪn"
                },
                {
                    "word": "stock",
                    "ipa_us": "stɑk"
                }
            ]
        },
        {
            "text": "I'd like half a pound of sliced turkey, please.",
            "words": [
                {
                    "word": "I'd",
                    "ipa_us": "aɪd"
                },
                {
                    "word": "like",
                    "ipa_us": "laɪk"
                },
                {
                    "word": "half",
                    "ipa_us": "hæf"
                },
                {
                    "word": "a",
                    "ipa_us": "ə"
                },
                {
                    "word": "pound",
                    "ipa_us": "paʊnd"
                },
                {
                    "word": "of",
                    "ipa_us": "əv"
                },
                {
                    "word": "sliced",
                    "ipa_us": "slaɪst"
                },
                {
                    "word": "turkey",
                    "ipa_us": "ˈtərki"
                },
                {
                    "word": "please",
                    "ipa_us": "pliz"
                }
            ]
        },
        {
            "text": "Is this item on sale this week?",
            "words": [
                {
                    "word": "Is",
                    "ipa_us": "ɪz"
                },
                {
                    "word": "this",
                    "ipa_us": "ðɪs"
                },
                {
                    "word": "item",
                    "ipa_us": "ˈaɪtəm"
                },
                {
                    "word": "on",
                    "ipa_us": "ɔn"
                },
                {
                    "word": "sale",
                    "ipa_us": "seɪl"
                },
                {
                    "word": "this",
                    "ipa_us": "ðɪs"
                },
                {
                    "word": "week",
                    "ipa_us": "wik"
                }
            ]
        }
    ],
    "doctor": [
        {
            "text": "I've been having a headache for about three days now.",
            "words": [
                {
                    "word": "I've",
                    "ipa_us": "aɪv"
                },
                {
                    "word": "been",
                    "ipa_us": "bɪn"
                },
                {
                    "word": "having",
                    "ipa_us": "ˈhævɪŋ"
                },
                {
                    "word": "a",
                    "ipa_us": "ə"
                },
                {
                    "word": "headache",
                    "ipa_us": "ˈhɛˌdeɪk"
                },
                {
                    "word": "for",
                    "ipa_us": "fər"
                },
                {
                    "word": "about",
                    "ipa_us": "əˈbaʊt"
                },
                {
                    "word": "three",
                    "ipa_us": "θri"
                },
                {
                    "word": "days",
                    "ipa_us": "deɪz"
                },
                {
                    "word": "now",
                    "ipa_us": "naʊ"
                }
            ]
        },
        {
            "text": "The pain gets worse in the morning and evening.",
            "words": [
                {
                    "word": "The",
                    "ipa_us": "ðə"
                },
                {
                    "word": "pain",
                    "ipa_us": "peɪn"
                },
                {
                    "word": "gets",
                    "ipa_us": "gɪts"
                },
                {
                    "word": "worse",
                    "ipa_us": "wərs"
                },
                {
                    "word": "in",
                    "ipa_us": "ɪn"
                },
                {
                    "word": "the",
                    "ipa_us": "ðə"
                },
                {
                    "word": "morning",
                    "ipa_us": "ˈmɔrnɪŋ"
                },
                {
                    "word": "and",
                    "ipa_us": "ənd"
                },
                {
                    "word": "evening",
                    "ipa_us": "ˈivnɪŋ"
                }
            ]
        },
        {
            "text": "I'm not currently taking any medication.",
            "words": [
                {
                    "word": "I'm",
                    "ipa_us": "əm"
                },
                {
                    "word": "not",
                    "ipa_us": "nɑt"
                },
                {
                    "word": "currently",
                    "ipa_us": "ˈkərəntli"
                },
                {
                    "word": "taking",
                    "ipa_us": "ˈteɪkɪŋ"
                },
                {
                    "word": "any",
                    "ipa_us": "ˈɛni"
                },
                {
                    "word": "medication",
                    "ipa_us": "ˌmɛdəˈkeɪʃən"
                }
            ]
        },
        {
            "text": "Should I schedule a follow-up appointment?",
            "words": [
                {
                    "word": "Should",
                    "ipa_us": "ʃʊd"
                },
                {
                    "word": "I",
                    "ipa_us": "aɪ"
                },
                {
                    "word": "schedule",
                    "ipa_us": "ˈskɛʤʊl"
                },
                {
                    "word": "a",
                    "ipa_us": "ə"
                },
                {
                    "word": "follow-up",
                    "ipa_us": "ˈfɑloʊˌəp"
                },
                {
                    "word": "appointment",
                    "ipa_us": "əˈpɔɪntmənt"
                }
            ]
        }
    ],
    "restaurant": [
        {
            "text": "I'd like to start with the soup of the day, please.",
            "words": [
                {
                    "word": "I'd",
                    "ipa_us": "aɪd"
                },
                {
                    "word": "like",
                    "ipa_us": "laɪk"
                },
                {
                    "word": "to",
                    "ipa_us": "tɪ"
                },
                {
                    "word": "start",
                    "ipa_us": "stɑrt"
                },
                {
                    "word": "with",
                    "ipa_us": "wɪθ"
                },
                {
                    "word": "the",
                    "ipa_us": "ðə"
                },
                {
                    "word": "soup",
                    "ipa_us": "sup"
                },
                {
                    "word": "of",
                    "ipa_us": "əv"
                },
                {
                    "word": "the",
                    "ipa_us": "ðə"
                },
                {
                    "word": "day",
                    "ipa_us": "deɪ"
                },
                {
                    "word": "please",
                    "ipa_us": "pliz"
                }
            ]
        },
        {
            "text": "Could you tell me what the chef recommends?",
            "words": [
                {
                    "word": "Could",
                    "ipa_us": "kʊd"
                },
                {
                    "word": "you",
                    "ipa_us": "ju"
                },
                {
                    "word": "tell",
                    "ipa_us": "tɛl"
                },
                {
                    "word": "me",
                    "ipa_us": "mi"
                },
                {
                    "word": "what",
                    "ipa_us": "wət"
                },
                {
                    "word": "the",
                    "ipa_us": "ðə"
                },
                {
                    "word": "chef",
                    "ipa_us": "ʃɛf"
                },
                {
                    "word": "recommends",
                    "ipa_us": "ˌrɛkəˈmɛndz"
                }
            ]
        },
        {
            "text": "I have a nut allergy. Is this dish safe for me?",
            "words": [
                {
                    "word": "I",
                    "ipa_us": "aɪ"
                },
                {
                    "word": "have",
                    "ipa_us": "hæv"
                },
                {
                    "word": "a",
                    "ipa_us": "ə"
                },
                {
                    "word": "nut",
                    "ipa_us": "nət"
                },
                {
                    "word": "allergy",
                    "ipa_us": "ˈælərʤi"
                },
                {
                    "word": "Is",
                    "ipa_us": "ɪz"
                },
                {
                    "word": "this",
                    "ipa_us": "ðɪs"
                },
                {
                    "word": "dish",
                    "ipa_us": "dɪʃ"
                },
                {
                    "word": "safe",
                    "ipa_us": "seɪf"
                },
                {
                    "word": "for",
                    "ipa_us": "fər"
                },
                {
                    "word": "me",
                    "ipa_us": "mi"
                }
            ]
        },
        {
            "text": "Could we get the check when you have a moment?",
            "words": [
                {
                    "word": "Could",
                    "ipa_us": "kʊd"
                },
                {
                    "word": "we",
                    "ipa_us": "wi"
                },
                {
                    "word": "get",
                    "ipa_us": "gɪt"
                },
                {
                    "word": "the",
                    "ipa_us": "ðə"
                },
                {
                    "word": "check",
                    "ipa_us": "ʧɛk"
                },
                {
                    "word": "when",
                    "ipa_us": "wɪn"
                },
                {
                    "word": "you",
                    "ipa_us": "ju"
                },
                {
                    "word": "have",
                    "ipa_us": "hæv"
                },
                {
                    "word": "a",
                    "ipa_us": "ə"
                },
                {
                    "word": "moment",
                    "ipa_us": "ˈmoʊmənt"
                }
            ]
        }
    ],
    "delivery": [
        {
            "text": "I'm in the building on the left side of the street.",
            "words": [
                {
                    "word": "I'm",
                    "ipa_us": "əm"
                },
                {
                    "word": "in",
                    "ipa_us": "ɪn"
                },
                {
                    "word": "the",
                    "ipa_us": "ðə"
                },
                {
                    "word": "building",
                    "ipa_us": "ˈbɪldɪŋ"
                },
                {
                    "word": "on",
                    "ipa_us": "ɔn"
                },
                {
                    "word": "the",
                    "ipa_us": "ðə"
                },
                {
                    "word": "left",
                    "ipa_us": "lɛft"
                },
                {
                    "word": "side",
                    "ipa_us": "saɪd"
                },
                {
                    "word": "of",
                    "ipa_us": "əv"
                },
                {
                    "word": "the",
                    "ipa_us": "ðə"
                },
                {
                    "word": "street",
                    "ipa_us": "strit"
                }
            ]
        },
        {
            "text": "You need to enter the code one two three four at the gate.",
            "words": [
                {
                    "word": "You",
                    "ipa_us": "ju"
                },
                {
                    "word": "need",
                    "ipa_us": "nid"
                },
                {
                    "word": "to",
                    "ipa_us": "tɪ"
                },
                {
                    "word": "enter",
                    "ipa_us": "ˈɛnər"
                },
                {
                    "word": "the",
                    "ipa_us": "ðə"
                },
                {
                    "word": "code",
                    "ipa_us": "koʊd"
                },
                {
                    "word": "one",
                    "ipa_us": "wən"
                },
                {
                    "word": "two",
                    "ipa_us": "tu"
                },
                {
                    "word": "three",
                    "ipa_us": "θri"
                },
                {
                    "word": "four",
                    "ipa_us": "fɔr"
                },
                {
                    "word": "at",
                    "ipa_us": "æt"
                },
                {
                    "word": "the",
                    "ipa_us": "ðə"
                },
                {
                    "word": "gate",
                    "ipa_us": "geɪt"
                }
            ]
        },
        {
            "text": "I'll come downstairs to meet you at the entrance.",
            "words": [
                {
                    "word": "I'll",
                    "ipa_us": "aɪl"
                },
                {
                    "word": "come",
                    "ipa_us": "kəm"
                },
                {
                    "word": "downstairs",
                    "ipa_us": "ˈdaʊnˈstɛrz"
                },
                {
                    "word": "to",
                    "ipa_us": "tɪ"
                },
                {
                    "word": "meet",
                    "ipa_us": "mit"
                },
                {
                    "word": "you",
                    "ipa_us": "ju"
                },
                {
                    "word": "at",
                    "ipa_us": "æt"
                },
                {
                    "word": "the",
                    "ipa_us": "ðə"
                },
                {
                    "word": "entrance",
                    "ipa_us": "ˈɛntrəns"
                }
            ]
        },
        {
            "text": "The apartment number is three zero five on the third floor.",
            "words": [
                {
                    "word": "The",
                    "ipa_us": "ðə"
                },
                {
                    "word": "apartment",
                    "ipa_us": "əˈpɑrtmənt"
                },
                {
                    "word": "number",
                    "ipa_us": "ˈnəmbər"
                },
                {
                    "word": "is",
                    "ipa_us": "ɪz"
                },
                {
                    "word": "three",
                    "ipa_us": "θri"
                },
                {
                    "word": "zero",
                    "ipa_us": "ˈziroʊ"
                },
                {
                    "word": "five",
                    "ipa_us": "faɪv"
                },
                {
                    "word": "on",
                    "ipa_us": "ɔn"
                },
                {
                    "word": "the",
                    "ipa_us": "ðə"
                },
                {
                    "word": "third",
                    "ipa_us": "θərd"
                },
                {
                    "word": "floor",
                    "ipa_us": "flɔr"
                }
            ]
        }
    ],
    "interview": [
        {
            "text": "I have three years of experience in software development.",
            "words": [
                {
                    "word": "I",
                    "ipa_us": "aɪ"
                },
                {
                    "word": "have",
                    "ipa_us": "hæv"
                },
                {
                    "word": "three",
                    "ipa_us": "θri"
                },
                {
                    "word": "years",
                    "ipa_us": "jɪrz"
                },
                {
                    "word": "of",
                    "ipa_us": "əv"
                },
                {
                    "word": "experience",
                    "ipa_us": "ɪkˈspɪriəns"
                },
                {
                    "word": "in",
                    "ipa_us": "ɪn"
                },
                {
                    "word": "software",
                    "ipa_us": "ˈsɔfˌwɛr"
                },
                {
                    "word": "development",
                    "ipa_us": "dɪˈvɛləpmənt"
                }
            ]
        },
        {
            "text": "My biggest strength is my ability to learn quickly.",
            "words": [
                {
                    "word": "My",
                    "ipa_us": "maɪ"
                },
                {
                    "word": "biggest",
                    "ipa_us": "ˈbɪgəst"
                },
                {
                    "word": "strength",
                    "ipa_us": "strɛŋθ"
                },
                {
                    "word": "is",
                    "ipa_us": "ɪz"
                },
                {
                    "word": "my",
                    "ipa_us": "maɪ"
                },
                {
                    "word": "ability",
                    "ipa_us": "əˈbɪləˌti"
                },
                {
                    "word": "to",
                    "ipa_us": "tɪ"
                },
                {
                    "word": "learn",
                    "ipa_us": "lərn"
                },
                {
                    "word": "quickly",
                    "ipa_us": "kˈwɪkli"
                }
            ]
        },
        {
            "text": "I led a team of five engineers on that project.",
            "words": [
                {
                    "word": "I",
                    "ipa_us": "aɪ"
                },
                {
                    "word": "led",
                    "ipa_us": "lɛd"
                },
                {
                    "word": "a",
                    "ipa_us": "ə"
                },
                {
                    "word": "team",
                    "ipa_us": "tim"
                },
                {
                    "word": "of",
                    "ipa_us": "əv"
                },
                {
                    "word": "five",
                    "ipa_us": "faɪv"
                },
                {
                    "word": "engineers",
                    "ipa_us": "ˈɛnʤəˈnɪrz"
                },
                {
                    "word": "on",
                    "ipa_us": "ɔn"
                },
                {
                    "word": "that",
                    "ipa_us": "ðət"
                },
                {
                    "word": "project",
                    "ipa_us": "ˈprɑʤɛkt"
                }
            ]
        },
        {
            "text": "I'm looking for a role where I can grow technically.",
            "words": [
                {
                    "word": "I'm",
                    "ipa_us": "əm"
                },
                {
                    "word": "looking",
                    "ipa_us": "ˈlʊkɪŋ"
                },
                {
                    "word": "for",
                    "ipa_us": "fər"
                },
                {
                    "word": "a",
                    "ipa_us": "ə"
                },
                {
                    "word": "role",
                    "ipa_us": "roʊl"
                },
                {
                    "word": "where",
                    "ipa_us": "wɛr"
                },
                {
                    "word": "I",
                    "ipa_us": "aɪ"
                },
                {
                    "word": "can",
                    "ipa_us": "kən"
                },
                {
                    "word": "grow",
                    "ipa_us": "groʊ"
                },
                {
                    "word": "technically",
                    "ipa_us": "ˈtɛknɪkəli"
                }
            ]
        }
    ],
    "meeting": [
        {
            "text": "I'd like to share a quick update on our progress.",
            "words": [
                {
                    "word": "I'd",
                    "ipa_us": "aɪd"
                },
                {
                    "word": "like",
                    "ipa_us": "laɪk"
                },
                {
                    "word": "to",
                    "ipa_us": "tɪ"
                },
                {
                    "word": "share",
                    "ipa_us": "ʃɛr"
                },
                {
                    "word": "a",
                    "ipa_us": "ə"
                },
                {
                    "word": "quick",
                    "ipa_us": "kwɪk"
                },
                {
                    "word": "update",
                    "ipa_us": "ˈəpˌdeɪt"
                },
                {
                    "word": "on",
                    "ipa_us": "ɔn"
                },
                {
                    "word": "our",
                    "ipa_us": "ɑr"
                },
                {
                    "word": "progress",
                    "ipa_us": "ˈprɑˌgrɛs"
                }
            ]
        },
        {
            "text": "We're currently on track to meet the deadline.",
            "words": [
                {
                    "word": "We're",
                    "ipa_us": "wɪr"
                },
                {
                    "word": "currently",
                    "ipa_us": "ˈkərəntli"
                },
                {
                    "word": "on",
                    "ipa_us": "ɔn"
                },
                {
                    "word": "track",
                    "ipa_us": "træk"
                },
                {
                    "word": "to",
                    "ipa_us": "tɪ"
                },
                {
                    "word": "meet",
                    "ipa_us": "mit"
                },
                {
                    "word": "the",
                    "ipa_us": "ðə"
                },
                {
                    "word": "deadline",
                    "ipa_us": "ˈdɛˌdlaɪn"
                }
            ]
        },
        {
            "text": "I think we should consider an alternative approach.",
            "words": [
                {
                    "word": "I",
                    "ipa_us": "aɪ"
                },
                {
                    "word": "think",
                    "ipa_us": "θɪŋk"
                },
                {
                    "word": "we",
                    "ipa_us": "wi"
                },
                {
                    "word": "should",
                    "ipa_us": "ʃʊd"
                },
                {
                    "word": "consider",
                    "ipa_us": "kənˈsɪdər"
                },
                {
                    "word": "an",
                    "ipa_us": "ən"
                },
                {
                    "word": "alternative",
                    "ipa_us": "ɔlˈtərnətɪv"
                },
                {
                    "word": "approach",
                    "ipa_us": "əˈproʊʧ"
                }
            ]
        },
        {
            "text": "Let me summarize the action items from today.",
            "words": [
                {
                    "word": "Let",
                    "ipa_us": "lɛt"
                },
                {
                    "word": "me",
                    "ipa_us": "mi"
                },
                {
                    "word": "summarize",
                    "ipa_us": "ˈsəmərˌaɪz"
                },
                {
                    "word": "the",
                    "ipa_us": "ðə"
                },
                {
                    "word": "action",
                    "ipa_us": "ˈækʃən"
                },
                {
                    "word": "items",
                    "ipa_us": "ˈaɪtəmz"
                },
                {
                    "word": "from",
                    "ipa_us": "frəm"
                },
                {
                    "word": "today",
                    "ipa_us": "təˈdeɪ"
                }
            ]
        }
    ],
    "coworker": [
        {
            "text": "Hey, do you want to grab coffee after this meeting?",
            "words": [
                {
                    "word": "Hey",
                    "ipa_us": "heɪ"
                },
                {
                    "word": "do",
                    "ipa_us": "du"
                },
                {
                    "word": "you",
                    "ipa_us": "ju"
                },
                {
                    "word": "want",
                    "ipa_us": "wɔnt"
                },
                {
                    "word": "to",
                    "ipa_us": "tɪ"
                },
                {
                    "word": "grab",
                    "ipa_us": "græb"
                },
                {
                    "word": "coffee",
                    "ipa_us": "ˈkɔfi"
                },
                {
                    "word": "after",
                    "ipa_us": "ˈæftər"
                },
                {
                    "word": "this",
                    "ipa_us": "ðɪs"
                },
                {
                    "word": "meeting",
                    "ipa_us": "ˈmitɪŋ"
                }
            ]
        },
        {
            "text": "I'm thinking about taking a vacation next month.",
            "words": [
                {
                    "word": "I'm",
                    "ipa_us": "əm"
                },
                {
                    "word": "thinking",
                    "ipa_us": "ˈθɪŋkɪŋ"
                },
                {
                    "word": "about",
                    "ipa_us": "əˈbaʊt"
                },
                {
                    "word": "taking",
                    "ipa_us": "ˈteɪkɪŋ"
                },
                {
                    "word": "a",
                    "ipa_us": "ə"
                },
                {
                    "word": "vacation",
                    "ipa_us": "veɪˈkeɪʃən"
                },
                {
                    "word": "next",
                    "ipa_us": "nɛkst"
                },
                {
                    "word": "month",
                    "ipa_us": "mənθ"
                }
            ]
        },
        {
            "text": "Have you tried the new restaurant down the street?",
            "words": [
                {
                    "word": "Have",
                    "ipa_us": "hæv"
                },
                {
                    "word": "you",
                    "ipa_us": "ju"
                },
                {
                    "word": "tried",
                    "ipa_us": "traɪd"
                },
                {
                    "word": "the",
                    "ipa_us": "ðə"
                },
                {
                    "word": "new",
                    "ipa_us": "nu"
                },
                {
                    "word": "restaurant",
                    "ipa_us": "ˈrɛˌstrɑnt"
                },
                {
                    "word": "down",
                    "ipa_us": "daʊn"
                },
                {
                    "word": "the",
                    "ipa_us": "ðə"
                },
                {
                    "word": "street",
                    "ipa_us": "strit"
                }
            ]
        },
        {
            "text": "The deadline got pushed back to next Friday.",
            "words": [
                {
                    "word": "The",
                    "ipa_us": "ðə"
                },
                {
                    "word": "deadline",
                    "ipa_us": "ˈdɛˌdlaɪn"
                },
                {
                    "word": "got",
                    "ipa_us": "gɑt"
                },
                {
                    "word": "pushed",
                    "ipa_us": "pʊʃt"
                },
                {
                    "word": "back",
                    "ipa_us": "bæk"
                },
                {
                    "word": "to",
                    "ipa_us": "tɪ"
                },
                {
                    "word": "next",
                    "ipa_us": "nɛkst"
                },
                {
                    "word": "Friday",
                    "ipa_us": "ˈfraɪˌdeɪ"
                }
            ]
        }
    ],
    "phone_call": [
        {
            "text": "Thank you for taking the time to speak with me today.",
            "words": [
                {
                    "word": "Thank",
                    "ipa_us": "θæŋk"
                },
                {
                    "word": "you",
                    "ipa_us": "ju"
                },
                {
                    "word": "for",
                    "ipa_us": "fər"
                },
                {
                    "word": "taking",
                    "ipa_us": "ˈteɪkɪŋ"
                },
                {
                    "word": "the",
                    "ipa_us": "ðə"
                },
                {
                    "word": "time",
                    "ipa_us": "taɪm"
                },
                {
                    "word": "to",
                    "ipa_us": "tɪ"
                },
                {
                    "word": "speak",
                    "ipa_us": "spik"
                },
                {
                    "word": "with",
                    "ipa_us": "wɪθ"
                },
                {
                    "word": "me",
                    "ipa_us": "mi"
                },
                {
                    "word": "today",
                    "ipa_us": "təˈdeɪ"
                }
            ]
        },
        {
            "text": "I'd like to discuss the timeline for the next deliverable.",
            "words": [
                {
                    "word": "I'd",
                    "ipa_us": "aɪd"
                },
                {
                    "word": "like",
                    "ipa_us": "laɪk"
                },
                {
                    "word": "to",
                    "ipa_us": "tɪ"
                },
                {
                    "word": "discuss",
                    "ipa_us": "dɪˈskəs"
                },
                {
                    "word": "the",
                    "ipa_us": "ðə"
                },
                {
                    "word": "timeline",
                    "ipa_us": "ˈtaɪmlaɪn"
                },
                {
                    "word": "for",
                    "ipa_us": "fər"
                },
                {
                    "word": "the",
                    "ipa_us": "ðə"
                },
                {
                    "word": "next",
                    "ipa_us": "nɛkst"
                },
                {
                    "word": "deliverable",
                    "ipa_us": "dɪˈlɪvərəbəl"
                }
            ]
        },
        {
            "text": "Could you send me that in writing after our call?",
            "words": [
                {
                    "word": "Could",
                    "ipa_us": "kʊd"
                },
                {
                    "word": "you",
                    "ipa_us": "ju"
                },
                {
                    "word": "send",
                    "ipa_us": "sɛnd"
                },
                {
                    "word": "me",
                    "ipa_us": "mi"
                },
                {
                    "word": "that",
                    "ipa_us": "ðət"
                },
                {
                    "word": "in",
                    "ipa_us": "ɪn"
                },
                {
                    "word": "writing",
                    "ipa_us": "ˈraɪtɪŋ"
                },
                {
                    "word": "after",
                    "ipa_us": "ˈæftər"
                },
                {
                    "word": "our",
                    "ipa_us": "ɑr"
                },
                {
                    "word": "call",
                    "ipa_us": "kɔl"
                }
            ]
        },
        {
            "text": "Let me confirm the next steps before we hang up.",
            "words": [
                {
                    "word": "Let",
                    "ipa_us": "lɛt"
                },
                {
                    "word": "me",
                    "ipa_us": "mi"
                },
                {
                    "word": "confirm",
                    "ipa_us": "kənˈfərm"
                },
                {
                    "word": "the",
                    "ipa_us": "ðə"
                },
                {
                    "word": "next",
                    "ipa_us": "nɛkst"
                },
                {
                    "word": "steps",
                    "ipa_us": "stɛps"
                },
                {
                    "word": "before",
                    "ipa_us": "ˌbiˈfɔr"
                },
                {
                    "word": "we",
                    "ipa_us": "wi"
                },
                {
                    "word": "hang",
                    "ipa_us": "hæŋ"
                },
                {
                    "word": "up",
                    "ipa_us": "əp"
                }
            ]
        }
    ],
    "salary": [
        {
            "text": "I appreciate the offer and I'm very excited about the role.",
            "words": [
                {
                    "word": "I",
                    "ipa_us": "aɪ"
                },
                {
                    "word": "appreciate",
                    "ipa_us": "əˈpriʃiˌeɪt"
                },
                {
                    "word": "the",
                    "ipa_us": "ðə"
                },
                {
                    "word": "offer",
                    "ipa_us": "ˈɔfər"
                },
                {
                    "word": "and",
                    "ipa_us": "ənd"
                },
                {
                    "word": "I'm",
                    "ipa_us": "əm"
                },
                {
                    "word": "very",
                    "ipa_us": "ˈvɛri"
                },
                {
                    "word": "excited",
                    "ipa_us": "ɪkˈsaɪtɪd"
                },
                {
                    "word": "about",
                    "ipa_us": "əˈbaʊt"
                },
                {
                    "word": "the",
                    "ipa_us": "ðə"
                },
                {
                    "word": "role",
                    "ipa_us": "roʊl"
                }
            ]
        },
        {
            "text": "Based on my research, I was hoping for something closer to ninety thousand.",
            "words": [
                {
                    "word": "Based",
                    "ipa_us": "beɪst"
                },
                {
                    "word": "on",
                    "ipa_us": "ɔn"
                },
                {
                    "word": "my",
                    "ipa_us": "maɪ"
                },
                {
                    "word": "research",
                    "ipa_us": "ˈrisərʧ"
                },
                {
                    "word": "I",
                    "ipa_us": "aɪ"
                },
                {
                    "word": "was",
                    "ipa_us": "wɑz"
                },
                {
                    "word": "hoping",
                    "ipa_us": "ˈhoʊpɪŋ"
                },
                {
                    "word": "for",
                    "ipa_us": "fər"
                },
                {
                    "word": "something",
                    "ipa_us": "ˈsəmθɪŋ"
                },
                {
                    "word": "closer",
                    "ipa_us": "ˈkloʊzər"
                },
                {
                    "word": "to",
                    "ipa_us": "tɪ"
                },
                {
                    "word": "ninety",
                    "ipa_us": "ˈnaɪnti"
                },
                {
                    "word": "thousand",
                    "ipa_us": "ˈθaʊzənd"
                }
            ]
        },
        {
            "text": "Could you tell me more about the equity package?",
            "words": [
                {
                    "word": "Could",
                    "ipa_us": "kʊd"
                },
                {
                    "word": "you",
                    "ipa_us": "ju"
                },
                {
                    "word": "tell",
                    "ipa_us": "tɛl"
                },
                {
                    "word": "me",
                    "ipa_us": "mi"
                },
                {
                    "word": "more",
                    "ipa_us": "mɔr"
                },
                {
                    "word": "about",
                    "ipa_us": "əˈbaʊt"
                },
                {
                    "word": "the",
                    "ipa_us": "ðə"
                },
                {
                    "word": "equity",
                    "ipa_us": "ˈɛkwəti"
                },
                {
                    "word": "package",
                    "ipa_us": "ˈpækɪʤ"
                }
            ]
        },
        {
            "text": "I'd like a few days to review the complete offer.",
            "words": [
                {
                    "word": "I'd",
                    "ipa_us": "aɪd"
                },
                {
                    "word": "like",
                    "ipa_us": "laɪk"
                },
                {
                    "word": "a",
                    "ipa_us": "ə"
                },
                {
                    "word": "few",
                    "ipa_us": "fju"
                },
                {
                    "word": "days",
                    "ipa_us": "deɪz"
                },
                {
                    "word": "to",
                    "ipa_us": "tɪ"
                },
                {
                    "word": "review",
                    "ipa_us": "ˌrivˈju"
                },
                {
                    "word": "the",
                    "ipa_us": "ðə"
                },
                {
                    "word": "complete",
                    "ipa_us": "kəmˈplit"
                },
                {
                    "word": "offer",
                    "ipa_us": "ˈɔfər"
                }
            ]
        }
    ],
    "airport": [
        {
            "text": "I'd like a window seat if one is available, please.",
            "words": [
                {
                    "word": "I'd",
                    "ipa_us": "aɪd"
                },
                {
                    "word": "like",
                    "ipa_us": "laɪk"
                },
                {
                    "word": "a",
                    "ipa_us": "ə"
                },
                {
                    "word": "window",
                    "ipa_us": "ˈwɪndoʊ"
                },
                {
                    "word": "seat",
                    "ipa_us": "sit"
                },
                {
                    "word": "if",
                    "ipa_us": "ɪf"
                },
                {
                    "word": "one",
                    "ipa_us": "wən"
                },
                {
                    "word": "is",
                    "ipa_us": "ɪz"
                },
                {
                    "word": "available",
                    "ipa_us": "əˈveɪləbəl"
                },
                {
                    "word": "please",
                    "ipa_us": "pliz"
                }
            ]
        },
        {
            "text": "I have one checked bag and one carry-on.",
            "words": [
                {
                    "word": "I",
                    "ipa_us": "aɪ"
                },
                {
                    "word": "have",
                    "ipa_us": "hæv"
                },
                {
                    "word": "one",
                    "ipa_us": "wən"
                },
                {
                    "word": "checked",
                    "ipa_us": "ʧɛkt"
                },
                {
                    "word": "bag",
                    "ipa_us": "bæg"
                },
                {
                    "word": "and",
                    "ipa_us": "ənd"
                },
                {
                    "word": "one",
                    "ipa_us": "wən"
                },
                {
                    "word": "carry-on",
                    "ipa_us": "ˈkɛriˌɑn"
                }
            ]
        },
        {
            "text": "What time does boarding start for my flight?",
            "words": [
                {
                    "word": "What",
                    "ipa_us": "wət"
                },
                {
                    "word": "time",
                    "ipa_us": "taɪm"
                },
                {
                    "word": "does",
                    "ipa_us": "dɪz"
                },
                {
                    "word": "boarding",
                    "ipa_us": "ˈbɔrdɪŋ"
                },
                {
                    "word": "start",
                    "ipa_us": "stɑrt"
                },
                {
                    "word": "for",
                    "ipa_us": "fər"
                },
                {
                    "word": "my",
                    "ipa_us": "maɪ"
                },
                {
                    "word": "flight",
                    "ipa_us": "flaɪt"
                }
            ]
        },
        {
            "text": "Is there a lounge I can access with this ticket?",
            "words": [
                {
                    "word": "Is",
                    "ipa_us": "ɪz"
                },
                {
                    "word": "there",
                    "ipa_us": "ðɛr"
                },
                {
                    "word": "a",
                    "ipa_us": "ə"
                },
                {
                    "word": "lounge",
                    "ipa_us": "laʊnʤ"
                },
                {
                    "word": "I",
                    "ipa_us": "aɪ"
                },
                {
                    "word": "can",
                    "ipa_us": "kən"
                },
                {
                    "word": "access",
                    "ipa_us": "ˈækˌsɛs"
                },
                {
                    "word": "with",
                    "ipa_us": "wɪθ"
                },
                {
                    "word": "this",
                    "ipa_us": "ðɪs"
                },
                {
                    "word": "ticket",
                    "ipa_us": "ˈtɪkɪt"
                }
            ]
        }
    ],
    "hotel": [
        {
            "text": "I have a reservation under the name Johnson for three nights.",
            "words": [
                {
                    "word": "I",
                    "ipa_us": "aɪ"
                },
                {
                    "word": "have",
                    "ipa_us": "hæv"
                },
                {
                    "word": "a",
                    "ipa_us": "ə"
                },
                {
                    "word": "reservation",
                    "ipa_us": "ˌrɛzərˈveɪʃən"
                },
                {
                    "word": "under",
                    "ipa_us": "ˈəndər"
                },
                {
                    "word": "the",
                    "ipa_us": "ðə"
                },
                {
                    "word": "name",
                    "ipa_us": "neɪm"
                },
                {
                    "word": "Johnson",
                    "ipa_us": "ˈʤɑnsən"
                },
                {
                    "word": "for",
                    "ipa_us": "fər"
                },
                {
                    "word": "three",
                    "ipa_us": "θri"
                },
                {
                    "word": "nights",
                    "ipa_us": "naɪts"
                }
            ]
        },
        {
            "text": "Is breakfast included with my room?",
            "words": [
                {
                    "word": "Is",
                    "ipa_us": "ɪz"
                },
                {
                    "word": "breakfast",
                    "ipa_us": "ˈbrɛkfəst"
                },
                {
                    "word": "included",
                    "ipa_us": "ˌɪnˈkludɪd"
                },
                {
                    "word": "with",
                    "ipa_us": "wɪθ"
                },
                {
                    "word": "my",
                    "ipa_us": "maɪ"
                },
                {
                    "word": "room",
                    "ipa_us": "rum"
                }
            ]
        },
        {
            "text": "Could you recommend a good restaurant nearby?",
            "words": [
                {
                    "word": "Could",
                    "ipa_us": "kʊd"
                },
                {
                    "word": "you",
                    "ipa_us": "ju"
                },
                {
                    "word": "recommend",
                    "ipa_us": "ˌrɛkəˈmɛnd"
                },
                {
                    "word": "a",
                    "ipa_us": "ə"
                },
                {
                    "word": "good",
                    "ipa_us": "gʊd"
                },
                {
                    "word": "restaurant",
                    "ipa_us": "ˈrɛˌstrɑnt"
                },
                {
                    "word": "nearby",
                    "ipa_us": "ˈnɪrˈbaɪ"
                }
            ]
        },
        {
            "text": "What time is checkout tomorrow morning?",
            "words": [
                {
                    "word": "What",
                    "ipa_us": "wət"
                },
                {
                    "word": "time",
                    "ipa_us": "taɪm"
                },
                {
                    "word": "is",
                    "ipa_us": "ɪz"
                },
                {
                    "word": "checkout",
                    "ipa_us": "ˈʧɛˌkaʊt"
                },
                {
                    "word": "tomorrow",
                    "ipa_us": "təˈmɑˌroʊ"
                },
                {
                    "word": "morning",
                    "ipa_us": "ˈmɔrnɪŋ"
                }
            ]
        }
    ],
    "directions": [
        {
            "text": "Excuse me, could you tell me how to get to the museum?",
            "words": [
                {
                    "word": "Excuse",
                    "ipa_us": "ɪkˈskjuz"
                },
                {
                    "word": "me",
                    "ipa_us": "mi"
                },
                {
                    "word": "could",
                    "ipa_us": "kʊd"
                },
                {
                    "word": "you",
                    "ipa_us": "ju"
                },
                {
                    "word": "tell",
                    "ipa_us": "tɛl"
                },
                {
                    "word": "me",
                    "ipa_us": "mi"
                },
                {
                    "word": "how",
                    "ipa_us": "haʊ"
                },
                {
                    "word": "to",
                    "ipa_us": "tɪ"
                },
                {
                    "word": "get",
                    "ipa_us": "gɪt"
                },
                {
                    "word": "to",
                    "ipa_us": "tɪ"
                },
                {
                    "word": "the",
                    "ipa_us": "ðə"
                },
                {
                    "word": "museum",
                    "ipa_us": "mˈjuziəm"
                }
            ]
        },
        {
            "text": "Is it within walking distance from here?",
            "words": [
                {
                    "word": "Is",
                    "ipa_us": "ɪz"
                },
                {
                    "word": "it",
                    "ipa_us": "ɪt"
                },
                {
                    "word": "within",
                    "ipa_us": "wɪˈθɪn"
                },
                {
                    "word": "walking",
                    "ipa_us": "ˈwɔkɪŋ"
                },
                {
                    "word": "distance",
                    "ipa_us": "ˈdɪstəns"
                },
                {
                    "word": "from",
                    "ipa_us": "frəm"
                },
                {
                    "word": "here",
                    "ipa_us": "hir"
                }
            ]
        },
        {
            "text": "Should I take the first or second left turn?",
            "words": [
                {
                    "word": "Should",
                    "ipa_us": "ʃʊd"
                },
                {
                    "word": "I",
                    "ipa_us": "aɪ"
                },
                {
                    "word": "take",
                    "ipa_us": "teɪk"
                },
                {
                    "word": "the",
                    "ipa_us": "ðə"
                },
                {
                    "word": "first",
                    "ipa_us": "fərst"
                },
                {
                    "word": "or",
                    "ipa_us": "ər"
                },
                {
                    "word": "second",
                    "ipa_us": "ˈsɛkənd"
                },
                {
                    "word": "left",
                    "ipa_us": "lɛft"
                },
                {
                    "word": "turn",
                    "ipa_us": "tərn"
                }
            ]
        },
        {
            "text": "Thank you so much for your help. I appreciate it.",
            "words": [
                {
                    "word": "Thank",
                    "ipa_us": "θæŋk"
                },
                {
                    "word": "you",
                    "ipa_us": "ju"
                },
                {
                    "word": "so",
                    "ipa_us": "soʊ"
                },
                {
                    "word": "much",
                    "ipa_us": "məʧ"
                },
                {
                    "word": "for",
                    "ipa_us": "fər"
                },
                {
                    "word": "your",
                    "ipa_us": "jʊr"
                },
                {
                    "word": "help",
                    "ipa_us": "hɛlp"
                },
                {
                    "word": "I",
                    "ipa_us": "aɪ"
                },
                {
                    "word": "appreciate",
                    "ipa_us": "əˈpriʃiˌeɪt"
                },
                {
                    "word": "it",
                    "ipa_us": "ɪt"
                }
            ]
        }
    ],
    "travel": [
        {
            "text": "I'd like to rent a mid-size sedan for five days.",
            "words": [
                {
                    "word": "I'd",
                    "ipa_us": "aɪd"
                },
                {
                    "word": "like",
                    "ipa_us": "laɪk"
                },
                {
                    "word": "to",
                    "ipa_us": "tɪ"
                },
                {
                    "word": "rent",
                    "ipa_us": "rɛnt"
                },
                {
                    "word": "a",
                    "ipa_us": "ə"
                },
                {
                    "word": "mid-size",
                    "ipa_us": "ˈmɪdˌsaɪz"
                },
                {
                    "word": "sedan",
                    "ipa_us": "səˈdæn"
                },
                {
                    "word": "for",
                    "ipa_us": "fər"
                },
                {
                    "word": "five",
                    "ipa_us": "faɪv"
                },
                {
                    "word": "days",
                    "ipa_us": "deɪz"
                }
            ]
        },
        {
            "text": "Does the insurance cover damage to the windshield?",
            "words": [
                {
                    "word": "Does",
                    "ipa_us": "dɪz"
                },
                {
                    "word": "the",
                    "ipa_us": "ðə"
                },
                {
                    "word": "insurance",
                    "ipa_us": "ˌɪnˈʃʊrəns"
                },
                {
                    "word": "cover",
                    "ipa_us": "ˈkəvər"
                },
                {
                    "word": "damage",
                    "ipa_us": "ˈdæmɪʤ"
                },
                {
                    "word": "to",
                    "ipa_us": "tɪ"
                },
                {
                    "word": "the",
                    "ipa_us": "ðə"
                },
                {
                    "word": "windshield",
                    "ipa_us": "ˈwɪndˌʃild"
                }
            ]
        },
        {
            "text": "What's your policy on returning the car with a full tank?",
            "words": [
                {
                    "word": "What's",
                    "ipa_us": "wəts"
                },
                {
                    "word": "your",
                    "ipa_us": "jʊr"
                },
                {
                    "word": "policy",
                    "ipa_us": "ˈpɑləsi"
                },
                {
                    "word": "on",
                    "ipa_us": "ɔn"
                },
                {
                    "word": "returning",
                    "ipa_us": "rɪˈtərnɪŋ"
                },
                {
                    "word": "the",
                    "ipa_us": "ðə"
                },
                {
                    "word": "car",
                    "ipa_us": "kɑr"
                },
                {
                    "word": "with",
                    "ipa_us": "wɪθ"
                },
                {
                    "word": "a",
                    "ipa_us": "ə"
                },
                {
                    "word": "full",
                    "ipa_us": "fʊl"
                },
                {
                    "word": "tank",
                    "ipa_us": "tæŋk"
                }
            ]
        },
        {
            "text": "Can I drop off the car at a different location?",
            "words": [
                {
                    "word": "Can",
                    "ipa_us": "kən"
                },
                {
                    "word": "I",
                    "ipa_us": "aɪ"
                },
                {
                    "word": "drop",
                    "ipa_us": "drɔp"
                },
                {
                    "word": "off",
                    "ipa_us": "ɔf"
                },
                {
                    "word": "the",
                    "ipa_us": "ðə"
                },
                {
                    "word": "car",
                    "ipa_us": "kɑr"
                },
                {
                    "word": "at",
                    "ipa_us": "æt"
                },
                {
                    "word": "a",
                    "ipa_us": "ə"
                },
                {
                    "word": "different",
                    "ipa_us": "ˈdɪfərənt"
                },
                {
                    "word": "location",
                    "ipa_us": "loʊˈkeɪʃən"
                }
            ]
        }
    ],
    "smalltalk": [
        {
            "text": "I've been really into cooking lately. It's so relaxing.",
            "words": [
                {
                    "word": "I've",
                    "ipa_us": "aɪv"
                },
                {
                    "word": "been",
                    "ipa_us": "bɪn"
                },
                {
                    "word": "really",
                    "ipa_us": "ˈrɪli"
                },
                {
                    "word": "into",
                    "ipa_us": "ˈɪntu"
                },
                {
                    "word": "cooking",
                    "ipa_us": "ˈkʊkɪŋ"
                },
                {
                    "word": "lately",
                    "ipa_us": "ˈleɪtli"
                },
                {
                    "word": "It's",
                    "ipa_us": "ɪts"
                },
                {
                    "word": "so",
                    "ipa_us": "soʊ"
                },
                {
                    "word": "relaxing",
                    "ipa_us": "rɪˈlæksɪŋ"
                }
            ]
        },
        {
            "text": "The weather has been great this week, hasn't it?",
            "words": [
                {
                    "word": "The",
                    "ipa_us": "ðə"
                },
                {
                    "word": "weather",
                    "ipa_us": "ˈwɛðər"
                },
                {
                    "word": "has",
                    "ipa_us": "həz"
                },
                {
                    "word": "been",
                    "ipa_us": "bɪn"
                },
                {
                    "word": "great",
                    "ipa_us": "greɪt"
                },
                {
                    "word": "this",
                    "ipa_us": "ðɪs"
                },
                {
                    "word": "week",
                    "ipa_us": "wik"
                },
                {
                    "word": "hasn't",
                    "ipa_us": "ˈhæzənt"
                },
                {
                    "word": "it",
                    "ipa_us": "ɪt"
                }
            ]
        },
        {
            "text": "I just started watching a new show on Netflix.",
            "words": [
                {
                    "word": "I",
                    "ipa_us": "aɪ"
                },
                {
                    "word": "just",
                    "ipa_us": "ʤɪst"
                },
                {
                    "word": "started",
                    "ipa_us": "ˈstɑrtɪd"
                },
                {
                    "word": "watching",
                    "ipa_us": "ˈwɑʧɪŋ"
                },
                {
                    "word": "a",
                    "ipa_us": "ə"
                },
                {
                    "word": "new",
                    "ipa_us": "nu"
                },
                {
                    "word": "show",
                    "ipa_us": "ʃoʊ"
                },
                {
                    "word": "on",
                    "ipa_us": "ɔn"
                },
                {
                    "word": "Netflix",
                    "ipa_us": "ˈnɛtflɪks"
                }
            ]
        },
        {
            "text": "Do you have any plans for the weekend?",
            "words": [
                {
                    "word": "Do",
                    "ipa_us": "du"
                },
                {
                    "word": "you",
                    "ipa_us": "ju"
                },
                {
                    "word": "have",
                    "ipa_us": "hæv"
                },
                {
                    "word": "any",
                    "ipa_us": "ˈɛni"
                },
                {
                    "word": "plans",
                    "ipa_us": "plænz"
                },
                {
                    "word": "for",
                    "ipa_us": "fər"
                },
                {
                    "word": "the",
                    "ipa_us": "ðə"
                },
                {
                    "word": "weekend",
                    "ipa_us": "ˈwiˌkɪnd"
                }
            ]
        }
    ],
    "party": [
        {
            "text": "It's nice to meet you! I'm a friend of a friend.",
            "words": [
                {
                    "word": "It's",
                    "ipa_us": "ɪts"
                },
                {
                    "word": "nice",
                    "ipa_us": "nis"
                },
                {
                    "word": "to",
                    "ipa_us": "tɪ"
                },
                {
                    "word": "meet",
                    "ipa_us": "mit"
                },
                {
                    "word": "you",
                    "ipa_us": "ju"
                },
                {
                    "word": "I'm",
                    "ipa_us": "əm"
                },
                {
                    "word": "a",
                    "ipa_us": "ə"
                },
                {
                    "word": "friend",
                    "ipa_us": "frɛnd"
                },
                {
                    "word": "of",
                    "ipa_us": "əv"
                },
                {
                    "word": "a",
                    "ipa_us": "ə"
                },
                {
                    "word": "friend",
                    "ipa_us": "frɛnd"
                }
            ]
        },
        {
            "text": "So what do you do for work? That sounds really interesting.",
            "words": [
                {
                    "word": "So",
                    "ipa_us": "soʊ"
                },
                {
                    "word": "what",
                    "ipa_us": "wət"
                },
                {
                    "word": "do",
                    "ipa_us": "du"
                },
                {
                    "word": "you",
                    "ipa_us": "ju"
                },
                {
                    "word": "do",
                    "ipa_us": "du"
                },
                {
                    "word": "for",
                    "ipa_us": "fər"
                },
                {
                    "word": "work",
                    "ipa_us": "wərk"
                },
                {
                    "word": "That",
                    "ipa_us": "ðət"
                },
                {
                    "word": "sounds",
                    "ipa_us": "saʊnz"
                },
                {
                    "word": "really",
                    "ipa_us": "ˈrɪli"
                },
                {
                    "word": "interesting",
                    "ipa_us": "ˈɪntəˌrɛstɪŋ"
                }
            ]
        },
        {
            "text": "Have you been to one of these parties before?",
            "words": [
                {
                    "word": "Have",
                    "ipa_us": "hæv"
                },
                {
                    "word": "you",
                    "ipa_us": "ju"
                },
                {
                    "word": "been",
                    "ipa_us": "bɪn"
                },
                {
                    "word": "to",
                    "ipa_us": "tɪ"
                },
                {
                    "word": "one",
                    "ipa_us": "wən"
                },
                {
                    "word": "of",
                    "ipa_us": "əv"
                },
                {
                    "word": "these",
                    "ipa_us": "ðiz"
                },
                {
                    "word": "parties",
                    "ipa_us": "ˈpɑrtiz"
                },
                {
                    "word": "before",
                    "ipa_us": "ˌbiˈfɔr"
                }
            ]
        },
        {
            "text": "We should definitely exchange numbers and hang out sometime.",
            "words": [
                {
                    "word": "We",
                    "ipa_us": "wi"
                },
                {
                    "word": "should",
                    "ipa_us": "ʃʊd"
                },
                {
                    "word": "definitely",
                    "ipa_us": "ˈdɛfənətli"
                },
                {
                    "word": "exchange",
                    "ipa_us": "ɪksˈʧeɪnʤ"
                },
                {
                    "word": "numbers",
                    "ipa_us": "ˈnəmbərz"
                },
                {
                    "word": "and",
                    "ipa_us": "ənd"
                },
                {
                    "word": "hang",
                    "ipa_us": "hæŋ"
                },
                {
                    "word": "out",
                    "ipa_us": "aʊt"
                },
                {
                    "word": "sometime",
                    "ipa_us": "ˈsəmˌtaɪm"
                }
            ]
        }
    ],
    "neighbor": [
        {
            "text": "Hi there! The neighborhood seems really nice and quiet.",
            "words": [
                {
                    "word": "Hi",
                    "ipa_us": "haɪ"
                },
                {
                    "word": "there",
                    "ipa_us": "ðɛr"
                },
                {
                    "word": "The",
                    "ipa_us": "ðə"
                },
                {
                    "word": "neighborhood",
                    "ipa_us": "ˈneɪbərˌhʊd"
                },
                {
                    "word": "seems",
                    "ipa_us": "simz"
                },
                {
                    "word": "really",
                    "ipa_us": "ˈrɪli"
                },
                {
                    "word": "nice",
                    "ipa_us": "nis"
                },
                {
                    "word": "and",
                    "ipa_us": "ənd"
                },
                {
                    "word": "quiet",
                    "ipa_us": "kwaɪət"
                }
            ]
        },
        {
            "text": "Do you know if there's a good coffee shop nearby?",
            "words": [
                {
                    "word": "Do",
                    "ipa_us": "du"
                },
                {
                    "word": "you",
                    "ipa_us": "ju"
                },
                {
                    "word": "know",
                    "ipa_us": "noʊ"
                },
                {
                    "word": "if",
                    "ipa_us": "ɪf"
                },
                {
                    "word": "there's",
                    "ipa_us": "ðɛrz"
                },
                {
                    "word": "a",
                    "ipa_us": "ə"
                },
                {
                    "word": "good",
                    "ipa_us": "gʊd"
                },
                {
                    "word": "coffee",
                    "ipa_us": "ˈkɔfi"
                },
                {
                    "word": "shop",
                    "ipa_us": "ʃɑp"
                },
                {
                    "word": "nearby",
                    "ipa_us": "ˈnɪrˈbaɪ"
                }
            ]
        },
        {
            "text": "I noticed there's a park down the street. Is it nice?",
            "words": [
                {
                    "word": "I",
                    "ipa_us": "aɪ"
                },
                {
                    "word": "noticed",
                    "ipa_us": "ˈnoʊtɪst"
                },
                {
                    "word": "there's",
                    "ipa_us": "ðɛrz"
                },
                {
                    "word": "a",
                    "ipa_us": "ə"
                },
                {
                    "word": "park",
                    "ipa_us": "pɑrk"
                },
                {
                    "word": "down",
                    "ipa_us": "daʊn"
                },
                {
                    "word": "the",
                    "ipa_us": "ðə"
                },
                {
                    "word": "street",
                    "ipa_us": "strit"
                },
                {
                    "word": "Is",
                    "ipa_us": "ɪz"
                },
                {
                    "word": "it",
                    "ipa_us": "ɪt"
                },
                {
                    "word": "nice",
                    "ipa_us": "nis"
                }
            ]
        },
        {
            "text": "Thanks for the tip! I'll definitely check it out.",
            "words": [
                {
                    "word": "Thanks",
                    "ipa_us": "θæŋks"
                },
                {
                    "word": "for",
                    "ipa_us": "fər"
                },
                {
                    "word": "the",
                    "ipa_us": "ðə"
                },
                {
                    "word": "tip",
                    "ipa_us": "tɪp"
                },
                {
                    "word": "I'll",
                    "ipa_us": "aɪl"
                },
                {
                    "word": "definitely",
                    "ipa_us": "ˈdɛfənətli"
                },
                {
                    "word": "check",
                    "ipa_us": "ʧɛk"
                },
                {
                    "word": "it",
                    "ipa_us": "ɪt"
                },
                {
                    "word": "out",
                    "ipa_us": "aʊt"
                }
            ]
        }
    ],
    "gym": [
        {
            "text": "I usually work out about four times a week.",
            "words": [
                {
                    "word": "I",
                    "ipa_us": "aɪ"
                },
                {
                    "word": "usually",
                    "ipa_us": "ˈjuʒəwəli"
                },
                {
                    "word": "work",
                    "ipa_us": "wərk"
                },
                {
                    "word": "out",
                    "ipa_us": "aʊt"
                },
                {
                    "word": "about",
                    "ipa_us": "əˈbaʊt"
                },
                {
                    "word": "four",
                    "ipa_us": "fɔr"
                },
                {
                    "word": "times",
                    "ipa_us": "taɪmz"
                },
                {
                    "word": "a",
                    "ipa_us": "ə"
                },
                {
                    "word": "week",
                    "ipa_us": "wik"
                }
            ]
        },
        {
            "text": "I've been focusing on building upper body strength.",
            "words": [
                {
                    "word": "I've",
                    "ipa_us": "aɪv"
                },
                {
                    "word": "been",
                    "ipa_us": "bɪn"
                },
                {
                    "word": "focusing",
                    "ipa_us": "ˈfoʊkɪsɪŋ"
                },
                {
                    "word": "on",
                    "ipa_us": "ɔn"
                },
                {
                    "word": "building",
                    "ipa_us": "ˈbɪldɪŋ"
                },
                {
                    "word": "upper",
                    "ipa_us": "ˈəpər"
                },
                {
                    "word": "body",
                    "ipa_us": "ˈbɑdi"
                },
                {
                    "word": "strength",
                    "ipa_us": "strɛŋθ"
                }
            ]
        },
        {
            "text": "Do you have any tips for improving my deadlift form?",
            "words": [
                {
                    "word": "Do",
                    "ipa_us": "du"
                },
                {
                    "word": "you",
                    "ipa_us": "ju"
                },
                {
                    "word": "have",
                    "ipa_us": "hæv"
                },
                {
                    "word": "any",
                    "ipa_us": "ˈɛni"
                },
                {
                    "word": "tips",
                    "ipa_us": "tɪps"
                },
                {
                    "word": "for",
                    "ipa_us": "fər"
                },
                {
                    "word": "improving",
                    "ipa_us": "ˌɪmˈpruvɪŋ"
                },
                {
                    "word": "my",
                    "ipa_us": "maɪ"
                },
                {
                    "word": "deadlift",
                    "ipa_us": "ˈdɛdˌlɪft"
                },
                {
                    "word": "form",
                    "ipa_us": "fɔrm"
                }
            ]
        },
        {
            "text": "I try to get at least eight hours of sleep for recovery.",
            "words": [
                {
                    "word": "I",
                    "ipa_us": "aɪ"
                },
                {
                    "word": "try",
                    "ipa_us": "traɪ"
                },
                {
                    "word": "to",
                    "ipa_us": "tɪ"
                },
                {
                    "word": "get",
                    "ipa_us": "gɪt"
                },
                {
                    "word": "at",
                    "ipa_us": "æt"
                },
                {
                    "word": "least",
                    "ipa_us": "list"
                },
                {
                    "word": "eight",
                    "ipa_us": "eɪt"
                },
                {
                    "word": "hours",
                    "ipa_us": "aʊərz"
                },
                {
                    "word": "of",
                    "ipa_us": "əv"
                },
                {
                    "word": "sleep",
                    "ipa_us": "slip"
                },
                {
                    "word": "for",
                    "ipa_us": "fər"
                },
                {
                    "word": "recovery",
                    "ipa_us": "rɪˈkəvəri"
                }
            ]
        }
    ]
}
